# Generated by Django 5.1 on 2024-08-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voicecommand',
            name='processed_text',
        ),
    ]
